repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.31.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
