// Code generated by mockery v2.42.1. DO NOT EDIT.

package auth

import (
	context "context"

	errs "github.com/raffops/chat/internal/errs"
	mock "github.com/stretchr/testify/mock"

	models "github.com/raffops/chat/internal/models"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *Repository) CreateUser(ctx context.Context, user models.User) (models.User, *errs.Err) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 *errs.Err
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (models.User, *errs.Err)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) *errs.Err); ok {
		r1 = rf(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.Err)
		}
	}

	return r0, r1
}

// Repository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Repository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *Repository_Expecter) CreateUser(ctx interface{}, user interface{}) *Repository_CreateUser_Call {
	return &Repository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *Repository_CreateUser_Call) Run(run func(ctx context.Context, user models.User)) *Repository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Repository_CreateUser_Call) Return(_a0 models.User, _a1 *errs.Err) *Repository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateUser_Call) RunAndReturn(run func(context.Context, models.User) (models.User, *errs.Err)) *Repository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, key, value
func (_m *Repository) GetUser(ctx context.Context, key string, value string) (models.User, *errs.Err) {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.User
	var r1 *errs.Err
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.User, *errs.Err)); ok {
		return rf(ctx, key, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.User); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *errs.Err); ok {
		r1 = rf(ctx, key, value)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.Err)
		}
	}

	return r0, r1
}

// Repository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type Repository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *Repository_Expecter) GetUser(ctx interface{}, key interface{}, value interface{}) *Repository_GetUser_Call {
	return &Repository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, key, value)}
}

func (_c *Repository_GetUser_Call) Run(run func(ctx context.Context, key string, value string)) *Repository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetUser_Call) Return(_a0 models.User, _a1 *errs.Err) *Repository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUser_Call) RunAndReturn(run func(context.Context, string, string) (models.User, *errs.Err)) *Repository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
